[2024-05-15T00:00:03.133+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: test_dag.inaccurate scheduled__2024-05-14T00:00:00+00:00 [queued]>
[2024-05-15T00:00:03.143+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: test_dag.inaccurate scheduled__2024-05-14T00:00:00+00:00 [queued]>
[2024-05-15T00:00:03.144+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-05-15T00:00:03.145+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-05-15T00:00:03.145+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-05-15T00:00:03.155+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): inaccurate> on 2024-05-14 00:00:00+00:00
[2024-05-15T00:00:03.160+0000] {standard_task_runner.py:55} INFO - Started process 20007 to run task
[2024-05-15T00:00:03.164+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'test_dag', 'inaccurate', 'scheduled__2024-05-14T00:00:00+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmp5q5xl4n1']
[2024-05-15T00:00:03.165+0000] {standard_task_runner.py:83} INFO - Job 26: Subtask inaccurate
[2024-05-15T00:00:03.239+0000] {task_command.py:388} INFO - Running <TaskInstance: test_dag.inaccurate scheduled__2024-05-14T00:00:00+00:00 [running]> on host f88edbb2c20c
[2024-05-15T00:00:03.292+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=test_dag
AIRFLOW_CTX_TASK_ID=inaccurate
AIRFLOW_CTX_EXECUTION_DATE=2024-05-14T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-14T00:00:00+00:00
[2024-05-15T00:00:03.294+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-05-15T00:00:03.295+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "echo 'inaccurate'"]
[2024-05-15T00:00:03.308+0000] {subprocess.py:86} INFO - Output:
[2024-05-15T00:00:03.311+0000] {subprocess.py:93} INFO - inaccurate
[2024-05-15T00:00:03.312+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-05-15T00:00:03.334+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=test_dag, task_id=inaccurate, execution_date=20240514T000000, start_date=20240515T000003, end_date=20240515T000003
[2024-05-15T00:00:03.378+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2024-05-15T00:00:03.394+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
